# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c46a9196d8a25d2d390851c8444e2ab9fb69b3cc14b5783c6d41d40de06d6549ebb2f3968326241aa62ea76e2e67cd496806bca9e2e1aa65fae7e94ace5217e

test:
  secret_key_base: 9381aef97d3d16b569ff33c29c8f30be2b288a48cfc1e31cfec847887048cbea35d6ce25f78a5d0ca8b868916732e46e7ae21434b6dd8a8faa3c1a43a82b8009

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
